### ISSUE TITLE
Pagination error while initialization

### ISSUE THREAD

**Issue by ultrasonicsoft** [janholinka/bs-table#10]
Hi There,

I am trying to use bs-table but getting below error.

Could you please let me know how to fix this issue?

Also, could you please share source code for demo project of your website?
http://bs-table.com/#/

I would like to apply themes as shown in that demo web site but on github repo it is not mentioned how to do it.

Thanks!

angular.js:11598 TypeError: t.children(...).size is not a function
    at Object.compile (http://localhost/libs/bs-table/bs-table.min.js:1:439)
    at ea (http://localhost/libs/javascripts/angular.min.js:62:454)
    at S (http://localhost/libs/javascripts/angular.min.js:52:139)
    at S (http://localhost/libs/javascripts/angular.min.js:52:270)
    at S (http://localhost/libs/javascripts/angular.min.js:52:270)
    at S (http://localhost/libs/javascripts/angular.min.js:52:270)
    at S (http://localhost/libs/javascripts/angular.min.js:52:270)
    at E (http://localhost/libs/javascripts/angular.min.js:50:162)
    at A.link (http://localhost/libs/javascripts/angular-route.min.js:7:224)
    at $ (http://localhost/libs/javascripts/angular.min.js:70:488) <table class="table table-hover table-bordered" bs-table="">

 ```
 <!-- Data Table -->
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script type="text/javascript" src="/libs/bs-table/bs-table.min.js"></script>
```
```

<table class="table table-hover table-bordered" bs-table>
                    <thead>
                        <tr>
                            <th ng-click="predicate='userName'; reverse=!reverse">First name</th>
                            <th ng-click="predicate='comments'; reverse=!reverse">Last name</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody> // you can use ng-repeat in tbody as below in tr html tag
                        <tr ng-repeat="contact in ctrl.myData | orderBy:predicate:reverse">
                            <td>{{contact.userName}}</td>
                            <td>{{contact.comments}}</td>
                            <td class="action-column">
                                <button type="button" class="btn btn-info btn-sm" ng-click="Edit(contact)">Edit</button>
                            </td>
                        </tr>
                    </tbody>
                </table>

```

![image](https://cloud.githubusercontent.com/assets/4145169/14061023/61bf5234-f39b-11e5-945e-65c7b7761f4b.png)

**Comment by janholinka** [comment]
Hi,

this error looks like you are missing jQuery library. Directive website is using Bootswatch API https://bootswatch.com/help/#api and code you can see in gh-pages branch of bs-table repository.

**Comment by ultrasonicsoft** [comment]
Cool.
Thanks!
