### ISSUE TITLE
t.is is not a function

### ISSUE THREAD

**Issue by racheliurui** [janholinka/bs-table#15]
Following the instructions to implement a table, the script giving  exception of "t.is is not a function" 
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
<script type="text/javascript" src="js/bs-table.min.js"></script>

**Comment by janholinka** [comment]
Hi,

thanks for using BsTable directive. Did you insert jQuery library?

**Comment by racheliurui** [comment]
Yes, I inserted jQuery library and referred to the same version on the demo.
If it's related to jQuery , I will have a check. Thanks
