### ISSUE TITLE
Unable to add <tfoot> for Pagination | Help is Appreciated

### ISSUE THREAD

**Issue by faran4engg** [janholinka/bs-table#16]
Hi,
I really loved this. I am new to Angular but this library helped me understand the logic quite easily.
But somehow, i am unable to add pagination control in my page.
Any help is greatly appreciated.
![bs_table_github_issue](https://cloud.githubusercontent.com/assets/24570234/21188938/f8113718-c242-11e6-83b2-b74e1c5cf562.JPG)

**Comment by janholinka** [comment]
Hi,

thanks for using bs-table. Pagination is automatically added to your table with tfoot element (you do not have to add tfoot element manually) based on total items in your contactList collection. Try to download gh-pages branch with working sample.

Hope it helps.

**Comment by faran4engg** [comment]
Hi Janholinka,

Thank you very much for your quick response.
I am new to this Angular world.
Can you please guide me with this gh-pages term and also to help me understand, why is it necessary to add in our existing bs-table.

**Comment by faran4engg** [comment]
Hi,

I also checked in the debugger tool in Chrome.
tfoot is not getting rendered.
Could you please help me solve this issue.
Many Thanks.
![tfoot_issue](https://cloud.githubusercontent.com/assets/24570234/21194849/73718e94-c257-11e6-8965-a62ee34ecfdb.JPG)

**Comment by janholinka** [comment]
Gh-pages is just working sample to compare with your code. You don't have to download it. Your problem is probably with uncompatible versions of AngularJS and jQuery source files. I haven't updated BsTable directive for a long time so it depends on specific versions (I will find some time to fix it) :/ 

I have created JSFiddle with working sample and proper versions of jQuery and AngularJS source files here: https://jsfiddle.net/janholinka/b0ztLwcb/

I hope it helps.

**Comment by faran4engg** [comment]
Whoaaa ! This is amazing. Thanks for creating that fiddle :+1: 
However, i have also created jsFiddle: https://jsfiddle.net/faran4engg/1mdo5eet/
I copied and pasted your code and also added external sources.
I am unable to see the expected result.
Could you guide me with the missing stuff please.
Thank you once again for the help till date :+1:

**Comment by janholinka** [comment]
Hi,

everythins is fine just set in javascript window load type to No wrap - in <head>. I am closing issue.

Thanks.
